/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrialRouteImport } from './routes/trial'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PersonalizationRouteImport } from './routes/personalization'
import { Route as PatientReportRouteImport } from './routes/patient-report'
import { Route as PatientEvolutionRouteImport } from './routes/patient-evolution'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImmunotherapiesRouteImport } from './routes/immunotherapies'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExportReportRouteImport } from './routes/export-report'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AdvancedSettingsRouteImport } from './routes/advanced-settings'
import { Route as AddImmunotherapyRouteImport } from './routes/add-immunotherapy'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientPatientIdRouteImport } from './routes/patient.$patientId'

const TrialRoute = TrialRouteImport.update({
  id: '/trial',
  path: '/trial',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizationRoute = PersonalizationRouteImport.update({
  id: '/personalization',
  path: '/personalization',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientReportRoute = PatientReportRouteImport.update({
  id: '/patient-report',
  path: '/patient-report',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientEvolutionRoute = PatientEvolutionRouteImport.update({
  id: '/patient-evolution',
  path: '/patient-evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmunotherapiesRoute = ImmunotherapiesRouteImport.update({
  id: '/immunotherapies',
  path: '/immunotherapies',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportReportRoute = ExportReportRouteImport.update({
  id: '/export-report',
  path: '/export-report',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedSettingsRoute = AdvancedSettingsRouteImport.update({
  id: '/advanced-settings',
  path: '/advanced-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AddImmunotherapyRoute = AddImmunotherapyRouteImport.update({
  id: '/add-immunotherapy',
  path: '/add-immunotherapy',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPatientIdRoute = PatientPatientIdRouteImport.update({
  id: '/patient/$patientId',
  path: '/patient/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/add-immunotherapy': typeof AddImmunotherapyRoute
  '/advanced-settings': typeof AdvancedSettingsRoute
  '/appointments': typeof AppointmentsRoute
  '/dashboard': typeof DashboardRoute
  '/export-report': typeof ExportReportRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/immunotherapies': typeof ImmunotherapiesRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/patient-evolution': typeof PatientEvolutionRoute
  '/patient-report': typeof PatientReportRoute
  '/personalization': typeof PersonalizationRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/trial': typeof TrialRoute
  '/patient/$patientId': typeof PatientPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/add-immunotherapy': typeof AddImmunotherapyRoute
  '/advanced-settings': typeof AdvancedSettingsRoute
  '/appointments': typeof AppointmentsRoute
  '/dashboard': typeof DashboardRoute
  '/export-report': typeof ExportReportRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/immunotherapies': typeof ImmunotherapiesRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/patient-evolution': typeof PatientEvolutionRoute
  '/patient-report': typeof PatientReportRoute
  '/personalization': typeof PersonalizationRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/trial': typeof TrialRoute
  '/patient/$patientId': typeof PatientPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/add-immunotherapy': typeof AddImmunotherapyRoute
  '/advanced-settings': typeof AdvancedSettingsRoute
  '/appointments': typeof AppointmentsRoute
  '/dashboard': typeof DashboardRoute
  '/export-report': typeof ExportReportRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/immunotherapies': typeof ImmunotherapiesRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/patient-evolution': typeof PatientEvolutionRoute
  '/patient-report': typeof PatientReportRoute
  '/personalization': typeof PersonalizationRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/trial': typeof TrialRoute
  '/patient/$patientId': typeof PatientPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/add-immunotherapy'
    | '/advanced-settings'
    | '/appointments'
    | '/dashboard'
    | '/export-report'
    | '/forgot-password'
    | '/help'
    | '/immunotherapies'
    | '/login'
    | '/notifications'
    | '/patient-evolution'
    | '/patient-report'
    | '/personalization'
    | '/plans'
    | '/profile'
    | '/register'
    | '/security'
    | '/settings'
    | '/teams'
    | '/trial'
    | '/patient/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/add-immunotherapy'
    | '/advanced-settings'
    | '/appointments'
    | '/dashboard'
    | '/export-report'
    | '/forgot-password'
    | '/help'
    | '/immunotherapies'
    | '/login'
    | '/notifications'
    | '/patient-evolution'
    | '/patient-report'
    | '/personalization'
    | '/plans'
    | '/profile'
    | '/register'
    | '/security'
    | '/settings'
    | '/teams'
    | '/trial'
    | '/patient/$patientId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/add-immunotherapy'
    | '/advanced-settings'
    | '/appointments'
    | '/dashboard'
    | '/export-report'
    | '/forgot-password'
    | '/help'
    | '/immunotherapies'
    | '/login'
    | '/notifications'
    | '/patient-evolution'
    | '/patient-report'
    | '/personalization'
    | '/plans'
    | '/profile'
    | '/register'
    | '/security'
    | '/settings'
    | '/teams'
    | '/trial'
    | '/patient/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AddImmunotherapyRoute: typeof AddImmunotherapyRoute
  AdvancedSettingsRoute: typeof AdvancedSettingsRoute
  AppointmentsRoute: typeof AppointmentsRoute
  DashboardRoute: typeof DashboardRoute
  ExportReportRoute: typeof ExportReportRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  ImmunotherapiesRoute: typeof ImmunotherapiesRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PatientEvolutionRoute: typeof PatientEvolutionRoute
  PatientReportRoute: typeof PatientReportRoute
  PersonalizationRoute: typeof PersonalizationRoute
  PlansRoute: typeof PlansRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  TeamsRoute: typeof TeamsRoute
  TrialRoute: typeof TrialRoute
  PatientPatientIdRoute: typeof PatientPatientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trial': {
      id: '/trial'
      path: '/trial'
      fullPath: '/trial'
      preLoaderRoute: typeof TrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalization': {
      id: '/personalization'
      path: '/personalization'
      fullPath: '/personalization'
      preLoaderRoute: typeof PersonalizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-report': {
      id: '/patient-report'
      path: '/patient-report'
      fullPath: '/patient-report'
      preLoaderRoute: typeof PatientReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-evolution': {
      id: '/patient-evolution'
      path: '/patient-evolution'
      fullPath: '/patient-evolution'
      preLoaderRoute: typeof PatientEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immunotherapies': {
      id: '/immunotherapies'
      path: '/immunotherapies'
      fullPath: '/immunotherapies'
      preLoaderRoute: typeof ImmunotherapiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-report': {
      id: '/export-report'
      path: '/export-report'
      fullPath: '/export-report'
      preLoaderRoute: typeof ExportReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced-settings': {
      id: '/advanced-settings'
      path: '/advanced-settings'
      fullPath: '/advanced-settings'
      preLoaderRoute: typeof AdvancedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-immunotherapy': {
      id: '/add-immunotherapy'
      path: '/add-immunotherapy'
      fullPath: '/add-immunotherapy'
      preLoaderRoute: typeof AddImmunotherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/$patientId': {
      id: '/patient/$patientId'
      path: '/patient/$patientId'
      fullPath: '/patient/$patientId'
      preLoaderRoute: typeof PatientPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AddImmunotherapyRoute: AddImmunotherapyRoute,
  AdvancedSettingsRoute: AdvancedSettingsRoute,
  AppointmentsRoute: AppointmentsRoute,
  DashboardRoute: DashboardRoute,
  ExportReportRoute: ExportReportRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  ImmunotherapiesRoute: ImmunotherapiesRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PatientEvolutionRoute: PatientEvolutionRoute,
  PatientReportRoute: PatientReportRoute,
  PersonalizationRoute: PersonalizationRoute,
  PlansRoute: PlansRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  TeamsRoute: TeamsRoute,
  TrialRoute: TrialRoute,
  PatientPatientIdRoute: PatientPatientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
