/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PatientEvolutionRouteImport } from './routes/patient-evolution'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImmunotherapiesRouteImport } from './routes/immunotherapies'
import { Route as ExportReportRouteImport } from './routes/export-report'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AddImmunotherapyRouteImport } from './routes/add-immunotherapy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientPatientIdRouteImport } from './routes/patient.$patientId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientEvolutionRoute = PatientEvolutionRouteImport.update({
  id: '/patient-evolution',
  path: '/patient-evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmunotherapiesRoute = ImmunotherapiesRouteImport.update({
  id: '/immunotherapies',
  path: '/immunotherapies',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportReportRoute = ExportReportRouteImport.update({
  id: '/export-report',
  path: '/export-report',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AddImmunotherapyRoute = AddImmunotherapyRouteImport.update({
  id: '/add-immunotherapy',
  path: '/add-immunotherapy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPatientIdRoute = PatientPatientIdRouteImport.update({
  id: '/patient/$patientId',
  path: '/patient/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-immunotherapy': typeof AddImmunotherapyRoute
  '/appointments': typeof AppointmentsRoute
  '/dashboard': typeof DashboardRoute
  '/export-report': typeof ExportReportRoute
  '/immunotherapies': typeof ImmunotherapiesRoute
  '/login': typeof LoginRoute
  '/patient-evolution': typeof PatientEvolutionRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/patient/$patientId': typeof PatientPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-immunotherapy': typeof AddImmunotherapyRoute
  '/appointments': typeof AppointmentsRoute
  '/dashboard': typeof DashboardRoute
  '/export-report': typeof ExportReportRoute
  '/immunotherapies': typeof ImmunotherapiesRoute
  '/login': typeof LoginRoute
  '/patient-evolution': typeof PatientEvolutionRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/patient/$patientId': typeof PatientPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-immunotherapy': typeof AddImmunotherapyRoute
  '/appointments': typeof AppointmentsRoute
  '/dashboard': typeof DashboardRoute
  '/export-report': typeof ExportReportRoute
  '/immunotherapies': typeof ImmunotherapiesRoute
  '/login': typeof LoginRoute
  '/patient-evolution': typeof PatientEvolutionRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/patient/$patientId': typeof PatientPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-immunotherapy'
    | '/appointments'
    | '/dashboard'
    | '/export-report'
    | '/immunotherapies'
    | '/login'
    | '/patient-evolution'
    | '/register'
    | '/settings'
    | '/patient/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-immunotherapy'
    | '/appointments'
    | '/dashboard'
    | '/export-report'
    | '/immunotherapies'
    | '/login'
    | '/patient-evolution'
    | '/register'
    | '/settings'
    | '/patient/$patientId'
  id:
    | '__root__'
    | '/'
    | '/add-immunotherapy'
    | '/appointments'
    | '/dashboard'
    | '/export-report'
    | '/immunotherapies'
    | '/login'
    | '/patient-evolution'
    | '/register'
    | '/settings'
    | '/patient/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddImmunotherapyRoute: typeof AddImmunotherapyRoute
  AppointmentsRoute: typeof AppointmentsRoute
  DashboardRoute: typeof DashboardRoute
  ExportReportRoute: typeof ExportReportRoute
  ImmunotherapiesRoute: typeof ImmunotherapiesRoute
  LoginRoute: typeof LoginRoute
  PatientEvolutionRoute: typeof PatientEvolutionRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  PatientPatientIdRoute: typeof PatientPatientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-evolution': {
      id: '/patient-evolution'
      path: '/patient-evolution'
      fullPath: '/patient-evolution'
      preLoaderRoute: typeof PatientEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immunotherapies': {
      id: '/immunotherapies'
      path: '/immunotherapies'
      fullPath: '/immunotherapies'
      preLoaderRoute: typeof ImmunotherapiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-report': {
      id: '/export-report'
      path: '/export-report'
      fullPath: '/export-report'
      preLoaderRoute: typeof ExportReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-immunotherapy': {
      id: '/add-immunotherapy'
      path: '/add-immunotherapy'
      fullPath: '/add-immunotherapy'
      preLoaderRoute: typeof AddImmunotherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/$patientId': {
      id: '/patient/$patientId'
      path: '/patient/$patientId'
      fullPath: '/patient/$patientId'
      preLoaderRoute: typeof PatientPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddImmunotherapyRoute: AddImmunotherapyRoute,
  AppointmentsRoute: AppointmentsRoute,
  DashboardRoute: DashboardRoute,
  ExportReportRoute: ExportReportRoute,
  ImmunotherapiesRoute: ImmunotherapiesRoute,
  LoginRoute: LoginRoute,
  PatientEvolutionRoute: PatientEvolutionRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  PatientPatientIdRoute: PatientPatientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
